// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4edY20BkM6Yuxjh9ASjbOcnVmjpu4UFU',
    appId: '1:952062815742:web:aff993ba41bcc0944d64af',
    messagingSenderId: '952062815742',
    projectId: 'echolens-a95ae',
    authDomain: 'echolens-a95ae.firebaseapp.com',
    storageBucket: 'echolens-a95ae.firebasestorage.app',
    measurementId: 'G-KTVWC2Q39B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnnyy_UaxXO0lSOi9jk83fctMybQl2mO4',
    appId: '1:952062815742:android:6782acb1e2d2242a4d64af',
    messagingSenderId: '952062815742',
    projectId: 'echolens-a95ae',
    storageBucket: 'echolens-a95ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8fAimHeqvKeqhQObYXl6rVdV2P--_sk',
    appId: '1:952062815742:ios:3347d6afe67b71324d64af',
    messagingSenderId: '952062815742',
    projectId: 'echolens-a95ae',
    storageBucket: 'echolens-a95ae.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );
}
