import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:htmltopdfwidgets/htmltopdfwidgets.dart' as hp;
import '../services/gemini_service.dart'; // Ensure this matches your path

class PdfUtils {
  static String _convertToHtml(String markdown) {
    RegExp boldExp = RegExp(r'\*\*(.*?)\*\*');
    String html = markdown.replaceAllMapped(boldExp, (match) => '<b>${match.group(1)}</b>');
    List<String> lines = html.split('\n');
    List<String> processedLines = [];
    for (var line in lines) {
      String l = line.trim();
      if (l.isEmpty) {
        processedLines.add('<br/>');
      } else {
        processedLines.add('<div>$l</div>');
      }
    }
    return processedLines.join('');
  }

  static Future<void> generateAndDownloadPdf(
    BuildContext context, 
    GeminiResponse response, 
    String queryTitle
  ) async {
    try {
      final pdf = pw.Document();
      final htmlContent = _convertToHtml(response.answer);
      final pdfWidgets = await hp.HTMLToPdf().convert(htmlContent);

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("EchoLens Profile Report", 
                      style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.amber800)),
                    pw.Text(DateTime.now().toString().split(' ')[0], 
                      style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              ...pdfWidgets,
              pw.SizedBox(height: 30),
              pw.Divider(thickness: 0.5, color: PdfColors.grey300),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text("Generated by EchoLens AI", style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
              ),
            ];
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'Profile_${queryTitle.replaceAll(' ', '_')}.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("PDF Error: ${e.toString()}")),
        );
      }
    }
  }
}